disabled_rules: # rule identifiers to exclude from running
 - trailing_whitespace
 - multiple_closures_with_trailing_closure
 - control_statement
 - syntactic_sugar

 
excluded: # paths to ignore during linting. Takes precedence over `included`.
 - Carthage
 - Pods
 
line_length:
    warning: 250
    error: 300
    ignores_function_declarations: true
    ignores_urls: true

function_body_length:
- 120 # warning
- 200 # error

cyclomatic_complexity:
- 30
- 50

file_length:
- 450
- 500

function_parameter_count:
- 7
- 10

identifier_name:
    min_length: 2
